/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        'open-sans': ['Open Sans', 'sans-serif'],
      },
    },
  },
  purge: {
    enabled: true,
    content: [
      './public/**/*.html',
      './public/*.html',
      './src/**/*.ts',
      './src/**/*.tsx',
      './src/*.ts',
      './src/**/*.html',
      './src/*.html',
      './utils/**/*.ts',
      './utils/**/*.tsx',
      './utils/*.ts',
      './utils/**/*.html',
      './utils/*.html',
      './public/**/*.ts',
      './public/*.ts',
      './index.html',
    ],
    options: {
      safelist: [
        'h-10',
        'w-10',
        'h-14',
        'w-14',
        'h-20',
        'w-20',
        'h-36',
        'w-36',
        'h-40',
        'w-40',
        'h-48',
        'w-48',
        'h-64',
        'w-64',
        'h-114',
        'w-114',
        'max-h-10',
        'max-w-10',
        'max-h-14',
        'max-w-14',
        'max-h-20',
        'max-w-20',
        'max-h-40',
        'max-w-40',
        'max-h-48',
        'max-w-48',
        'max-h-64',
        'max-w-64',
        'text-5xl',
        'text-6xl',
        'text-md',
        'rounded-full',
        'bg-gray-100',
        'dark:bg-gray-600',
        'text-gray-600',
        'dark:text-gray-300',
        'border-green-500',
        'border-red-500',
        'border-orange-500',
        'border-yellow-500',
        'bg-blue-800',
        'bg-blue-500',
        'h-[87vh]',
        'h-[93vh]',
        'h-[72vh]',
        'h-[6vh]',
        'hidden',
        'opacity-50',
        'cursor-not-allowed',
        'text-white',
        'bg-yellow-500',
      ],
    },
  },
  plugins: [],
};
